name: 'Terraform GitHub Actions'
on:
  - pull_request
jobs:
  pre-checks:
    name: 'pre-checks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: TFSec - Security Checks
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: .


